name: Build and Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18.8.0'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Type check backend
        run: deno check server.ts
        working-directory: server

      - name: Test backend
        run: deno test
        working-directory: server
      
      - name: Build frontend
        run: |
          npm ci --no-optional
          npm run build
        working-directory: ./client

      - name: Copy to dist folder
        run: |
          mkdir -p dist/client
          cp -r server/* dist/
          cp -r client/build/* dist/client/

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "q-p"
          entrypoint: "./server.ts"
          root: "dist"
